name: Integration Tests

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]
        node: ["18", "20"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Bun (Unix)
        if: runner.os != 'Windows'
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build Anvil
        run: cargo build --release

      - name: Run quick smoke tests
        run: cargo test --test integration_test smoke_test_basic_generation --release

      - name: Run performance benchmarks
        run: cargo test --test integration_test benchmark_generation_performance --release

      - name: Run template generation tests
        run: cargo test --test integration_test template_generation --release
        timeout-minutes: 20

      - name: Run shared component tests
        run: cargo test --test integration_test shared_components --release
        timeout-minutes: 15

      - name: Run service compatibility tests
        run: cargo test --test integration_test service_compatibility --release
        timeout-minutes: 15

      - name: Run build verification tests
        run: cargo test --test integration_test build_verification --release
        timeout-minutes: 25

      - name: Run complete integration suite
        run: cargo test --test integration_test run_complete_integration_test_suite --release
        timeout-minutes: 45

      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-${{ matrix.os }}-node${{ matrix.node }}
          path: |
            target/debug/
            /tmp/anvil-*
            logs/
          retention-days: 7

